import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React from 'react'
import InnerLayout from './InnerLayout'
import Footer from './footer'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={inter.className}>
        {/* <InnerLayout>{children}</InnerLayout> */}
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
